"""Markdown report assembler — converts structured findings into a final report."""

import json
from datetime import date
from pathlib import Path
from typing import Optional

from config import REPORTS_DIR


def _bullet_list(items: list[str], indent: int = 0) -> str:
    prefix = "  " * indent
    return "\n".join(f"{prefix}- {item}" for item in items) if items else f"{prefix}- Not disclosed"


def _safe(findings: dict, key: str, default: str = "_Not disclosed_") -> str:
    val = findings.get(key)
    if not val:
        return default
    return str(val).strip()


def _swot_section(swot: Optional[dict]) -> str:
    if not swot:
        return "_SWOT not completed._"
    s = swot.get("strengths", [])
    w = swot.get("weaknesses", [])
    o = swot.get("opportunities", [])
    t = swot.get("threats", [])
    return (
        "### Strengths\n"
        + _bullet_list(s)
        + "\n\n### Weaknesses\n"
        + _bullet_list(w)
        + "\n\n### Opportunities\n"
        + _bullet_list(o)
        + "\n\n### Threats\n"
        + _bullet_list(t)
    )


def _risk_flags_section(flags: Optional[list]) -> str:
    if not flags:
        return "_No material risk flags identified beyond standard disclosures._"
    lines = []
    for i, flag in enumerate(flags, 1):
        lines.append(f"{i}. {flag}")
    return "\n".join(lines)


def assemble_report(findings: dict, filing: dict) -> str:
    """Build the full Markdown report from findings and filing metadata."""
    today = date.today().isoformat()
    company = _safe(findings, "company_name", filing.get("company", "Unknown"))
    filed = _safe(findings, "filing_date", filing.get("filing_date", "Unknown"))
    rec = findings.get("investment_recommendation", "HOLD")
    rec_short = _safe(findings, "recommendation_rationale", "")
    # One-liner for header
    rec_oneliner = rec_short.split(".")[0] if "." in rec_short else rec_short[:120]

    # Recommendation badge
    badge_map = {"BUY": "🟢 **BUY**", "HOLD": "🟡 **HOLD**", "PASS": "🔴 **PASS**"}
    badge = badge_map.get(rec, f"**{rec}**")

    swot = findings.get("swot", {})
    risk_flags = findings.get("risk_flags", [])
    catalysts = findings.get("key_catalysts", [])
    risks_to_thesis = findings.get("key_risks_to_thesis", [])

    report = f"""# IPO S-1 Analysis: {company}

**Filed:** {filed} | **Analyst:** S-1 Analyst Agent | **Date:** {today}
**Recommendation:** {badge} — {rec_oneliner}

---

## Executive Summary

{_safe(findings, "executive_summary")}

---

## 1. Business Overview

{_safe(findings, "business_overview")}

## 2. Products & Services

{_safe(findings, "products_and_services")}

### Revenue Model

{_safe(findings, "revenue_model")}

---

## 3. Financial Analysis

{_safe(findings, "financial_analysis")}

### Key Metrics

{_safe(findings, "key_metrics")}

---

## 4. Valuation

{_safe(findings, "valuation")}

### Comparable Companies

{_safe(findings, "comparable_companies")}

---

## 5. Competitive Landscape

{_safe(findings, "competitive_landscape")}

### Moat Analysis

{_safe(findings, "moat_analysis")}

---

## 6. SWOT Analysis

{_swot_section(swot)}

---

## 7. Funding History & Key Backers

{_safe(findings, "funding_history")}

### Key Investors

{_safe(findings, "key_investors")}

---

## 8. Use of Proceeds

{_safe(findings, "use_of_proceeds")}

---

## 9. Cap Table & Dilution

{_safe(findings, "cap_table_summary")}

---

## 10. Risk Flags

{_risk_flags_section(risk_flags)}

---

## 11. Management Assessment

{_safe(findings, "management_assessment")}

---

## Investment Conclusion

### Bull Case

{_safe(findings, "bull_case")}

### Base Case

{_safe(findings, "base_case")}

### Bear Case

{_safe(findings, "bear_case")}

---

### Recommendation: {badge}

{_safe(findings, "recommendation_rationale")}

**Key Catalysts to Watch**
{_bullet_list(catalysts)}

**Key Risks to This Thesis**
{_bullet_list(risks_to_thesis)}

---

*Generated by IPO S-1 Analyst Agent | Model: {findings.get("_model", "claude-sonnet-4-6")} | Source: SEC EDGAR*
*This report is for informational purposes only and does not constitute investment advice.*
"""
    return report.strip()


def save_report(report: str, company: str) -> Path:
    """Write the report to REPORTS_DIR and return the path."""
    today = date.today().isoformat()
    safe_name = "".join(c if c.isalnum() or c in "-_" else "_" for c in company)
    filename = f"{safe_name}_{today}.md"
    path = REPORTS_DIR / filename
    path.write_text(report, encoding="utf-8")
    return path
